### ISSUE TITLE
README missing ‘the why’

### ISSUE THREAD

**Issue by danielbayley** [fabiospampinato/tiny-readdir#2]
As mentioned in https://github.com/sindresorhus/globby/issues/50#issuecomment-2030987298, I was wondering why the need for this package, as opposed to something like the following?

~~~ js
import {readdir} from 'node:fs/promises'

const recurse = path => !ignored(path) && path.isDirectory() ? recurse(path) : path)

readdir(cwd, { withFileTypes: true })
  .then(entries => entries
  .map(recurse))
~~~

**Comment by fabiospampinato** [comment]
Node's implementation is good for more limited use cases, it doesn't support globbing at all, it doesn't support ignoring folders (you can ignore them later, but if you don't ignore them as soon as possible you'll waste time looking into them) etc.

In general it's good to have control of these kinds of utility so that they can be tweaked in the future to expose more information if needed, the reason for `tiny-readdir-glob`'s existence was basically speeding-up prettier's CLI, more details [here](https://prettier.io/blog/2023/11/30/cli-deep-dive#finding-files-fast), but I'm sure some other use case would have popped up for me eventually.

**Comment by danielbayley** [comment]
Thanks for the clarification.

> Node's implementation … doesn't support globbing at all

Yeah that’s why I raised this here specifically, and not `tiny-readdir-glob`… Sorry, not sure why I had the glob pattern in there in the previous hurried example!

> it doesn't support ignoring folders (you can ignore them later, but if you don't ignore them as soon as possible you'll waste time looking into them

Sure, what I meant to be getting at was: could that aspect not be covered by making use of the `withFileTypes` option, something like the implementation (see *edit above)? @fabiospampinato

**Comment by fabiospampinato** [comment]
You could do that but it's not the same thing, for example I'm asking for the files in `/foo/bar` right after processing `/foo`, you are asking for those files after all the files at the root level have been processed.

In general if you go through the source code you'd find kind of a lot of code that those something that those 3 lines don't do, in general if you just look at the readme you'll see that my function returns lots of structured data that one just doesn't have with those 3 lines.

Depending on the use case though your solution may be enough.

**Comment by danielbayley** [comment]
Makes sense, yeah I guess as always it depends on the use case… Thanks for the insight.
